"""add_approval_status_to_attendance

Revision ID: 6c8dc8d04bd4
Revises: e7d293580976
Create Date: 2026-02-04 05:04:45.184170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8dc8d04bd4'
down_revision: Union[str, None] = 'e7d293580976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('approval_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'approval_status')
    # ### end Alembic commands ###
