"""add_manager_id_to_employees

Revision ID: e7d293580976
Revises: 6e7a5d0c6bd2
Create Date: 2026-02-03 08:55:03.566808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d293580976'
down_revision: Union[str, None] = '6e7a5d0c6bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###
